export const videos = [
    {
        id: 1,
        title: "React 18 Full Course for Beginners",
        channel: "Code Evolution",
        views: "1.2M views",
        time: "1 year ago",
        thumbnail: "https://picsum.photos/seed/react18/640/360",
    },
    {
        id: 2,
        title: "CSS Grid vs Flexbox: When to use which?",
        channel: "Frontend Mastery",
        views: "450K views",
        time: "2 months ago",
        thumbnail: "https://picsum.photos/seed/cssgrid/640/360",
    },
    {
        id: 3,
        title: "Build a Netflix Clone with Next.js 14",
        channel: "Dev Simplified",
        views: "890K views",
        time: "3 weeks ago",
        thumbnail: "https://picsum.photos/seed/netflix/640/360",
    },
    {
        id: 4,
        title: "TypeScript Crash Course 2024",
        channel: "Typed Code",
        views: "210K views",
        time: "5 days ago",
        thumbnail: "https://picsum.photos/seed/ts/640/360",
    },
    {
        id: 5,
        title: "Docker Explained in 100 Seconds",
        channel: "Fireship",
        views: "2.5M views",
        time: "1 year ago",
        thumbnail: "https://picsum.photos/seed/docker/640/360",
    },
    {
        id: 6,
        title: "Learn Tailwind CSS - Modern Styling",
        channel: "Design to Code",
        views: "120K views",
        time: "4 days ago",
        thumbnail: "https://picsum.photos/seed/tailwind/640/360",
    },
    {
        id: 7,
        title: "Node.js & Express API Tutorial",
        channel: "Backend Basic",
        views: "340K views",
        time: "6 months ago",
        thumbnail: "https://picsum.photos/seed/node/640/360",
    },
    {
        id: 8,
        title: "Understanding Async Await in JavaScript",
        channel: "JS Daily",
        views: "67K views",
        time: "2 weeks ago",
        thumbnail: "https://picsum.photos/seed/async/640/360",
    },
    {
        id: 9,
        title: "System Design Interview: Design Instagram",
        channel: "Tech Architecture",
        views: "1.8M views",
        time: "2 years ago",
        thumbnail: "https://picsum.photos/seed/sysdesign/640/360",
    },
    {
        id: 10,
        title: "Git & GitHub Crash Course",
        channel: "Version Control",
        views: "900K views",
        time: "8 months ago",
        thumbnail: "https://picsum.photos/seed/git/640/360",
    },
    {
        id: 11,
        title: "Python for Data Science - Full Course",
        channel: "Data Camp",
        views: "3.2M views",
        time: "3 years ago",
        thumbnail: "https://picsum.photos/seed/python/640/360",
    },
    {
        id: 12,
        title: "Figma to HTML/CSS Conversion",
        channel: "UI/UX Labs",
        views: "150K views",
        time: "1 month ago",
        thumbnail: "https://picsum.photos/seed/figma/640/360",
    },
    {
        id: 13,
        title: "Redux Toolkit - State Management",
        channel: "Redux Wizard",
        views: "80K views",
        time: "3 days ago",
        thumbnail: "https://picsum.photos/seed/redux/640/360",
    },
    {
        id: 14,
        title: "Web Accessibility (A11y) Guide",
        channel: "Inclusive Web",
        views: "45K views",
        time: "5 months ago",
        thumbnail: "https://picsum.photos/seed/a11y/640/360",
    },
    {
        id: 15,
        title: "VS Code Extensions You Need",
        channel: "Productivity Pro",
        views: "500K views",
        time: "1 week ago",
        thumbnail: "https://picsum.photos/seed/vscode/640/360",
    },
    {
        id: 16,
        title: "Day in the Life of a Software Engineer",
        channel: "Tech Vlogs",
        views: "4.5M views",
        time: "4 years ago",
        thumbnail: "https://picsum.photos/seed/daylife/640/360",
    },
    {
        id: 17,
        title: "MongoDB Crash Course",
        channel: "Database Dojo",
        views: "230K views",
        time: "9 months ago",
        thumbnail: "https://picsum.photos/seed/mongo/640/360",
    },
    {
        id: 18,
        title: "GraphQL vs REST API",
        channel: "API Central",
        views: "110K views",
        time: "2 months ago",
        thumbnail: "https://picsum.photos/seed/graphql/640/360",
    },
    {
        id: 19,
        title: "Rust vs Go - Which one to learn?",
        channel: "Lang War",
        views: "600K views",
        time: "1 year ago",
        thumbnail: "https://picsum.photos/seed/rustgo/640/360",
    },
    {
        id: 20,
        title: "Portfolio Review: Roast My Code",
        channel: "Senior Dev",
        views: "300K views",
        time: "2 weeks ago",
        thumbnail: "https://picsum.photos/seed/portfolio/640/360",
    },
    {
        id: 21,
        title: "Learn SvelteKit in 1 Hour",
        channel: "Svelte School",
        views: "55K views",
        time: "4 days ago",
        thumbnail: "https://picsum.photos/seed/svelte/640/360",
    },
    {
        id: 22,
        title: "AWS S3 & EC2 Tutorial",
        channel: "Cloud Guru",
        views: "780K views",
        time: "1 year ago",
        thumbnail: "https://picsum.photos/seed/aws/640/360",
    },
    {
        id: 23,
        title: "Clean Code Principles",
        channel: "Software Craft",
        views: "1.1M views",
        time: "3 years ago",
        thumbnail: "https://picsum.photos/seed/clean/640/360",
    },
    {
        id: 24,
        title: "Cybersecurity Basics for Beginners",
        channel: "Secured Life",
        views: "95K views",
        time: "2 months ago",
        thumbnail: "https://picsum.photos/seed/security/640/360",
    },
    {
        id: 25,
        title: "Machine Learning with JavaScript",
        channel: "AI Edge",
        views: "40K views",
        time: "1 week ago",
        thumbnail: "https://picsum.photos/seed/mljs/640/360",
    },
    {
        id: 26,
        title: "Cookies vs LocalStorage vs Session",
        channel: "Web Storage",
        views: "190K views",
        time: "6 months ago",
        thumbnail: "https://picsum.photos/seed/cookies/640/360",
    },
    {
        id: 27,
        title: "Vim in 100 Seconds",
        channel: "Terminal Velocity",
        views: "330K views",
        time: "1 year ago",
        thumbnail: "https://picsum.photos/seed/vim/640/360",
    },
    {
        id: 28,
        title: "Testing React Apps with Jest",
        channel: "QA Engineers",
        views: "85K views",
        time: "3 months ago",
        thumbnail: "https://picsum.photos/seed/jest/640/360",
    },
    {
        id: 29,
        title: "SQL vs NoSQL Explained",
        channel: "Data Decisions",
        views: "440K views",
        time: "2 years ago",
        thumbnail: "https://picsum.photos/seed/sqlnosql/640/360",
    },
    {
        id: 30,
        title: "Building a Chat App with Socket.io",
        channel: "Realtime Web",
        views: "270K views",
        time: "5 months ago",
        thumbnail: "https://picsum.photos/seed/socket/640/360",
    },
];